apiVersion: apps/v1
kind: Deployment
metadata:
  name: clean
  labels:
    app: clean
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clean
  template:
    metadata:
      labels:
        app: clean
    spec:
      containers:
        - name: clean
          image: skccuser15.azurecr.io/clean:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5